name: "FLZT 每日签到 + 转换流量"

on:
  schedule:
    - cron: "35 1 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          architecture: "x64"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run main.py
        env: 
            BASE_URL: ${{secrets.BASE_URL}}
            EMAIL: ${{secrets.EMAIL}}
            PASSWORD: ${{secrets.PASSWORD}}
            SERVER_KEY: ${{secrets.SERVER_KEY}}
        run: |
          python main.py
